### ISSUE TITLE
Aanmaak scherm voor factuur als financieel medewerker

### ISSUE THREAD

**Issue by sheepy-v2** [vampirewolfB/E3_Barroc_Intens_Team_Purple#13]

**Comment by vampirewolfB** [comment]
Als financieel medewerker wil ik makkelijk een factuur 
kunnen opstellen voor de aansluitkosten van een 
koffiezetapparaat. Zo voorkom ik dat iedere factuur er anders uitziet en 
dat ik mogelijk rekenfouten maak.
